In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('epldata_final.csv')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461 entries, 0 to 460
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        461 non-null    object
 1   club          461 non-null    object
 2   age           461 non-null    int64
 3   position      461 non-null    object
 4   position_cat  461 non-null    int64
 5   market_value  461 non-null    float64
 6   page_views    461 non-null    int64
 7   fpl_value     461 non-null    float64
 8   fpl_sel       461 non-null    object
 9   fpl_points    461 non-null    int64
 10  region        460 non-null    float64
 11  nationality   461 non-null    object
 12  new_foreign   461 non-null    int64
 13  age_cat       461 non-null    int64
 14  club_id       461 non-null    int64
 15  big_club      461 non-null    int64
 16  new_signing   461 non-null    int64
dtypes: float64(3), int64(9), object(5)
memory usage: 61.4+ KB

In [3]:
df2 = pd.read_csv('Premier_League_Player_Top_Scorers.csv')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rank    14 non-null     int64
 1   Player  14 non-null     object
 2   Stat    14 non-null     int64
dtypes: int64(2), object(1)
memory usage: 464.0+ bytes

In [4]:
df1.head()

,Player,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3.0,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2.0,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2.0,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1.0,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2.0,France,0,4,1,1,0

In [5]:
df2.head()

   Rank           Player  Stat
0     1    Mohamed Salah    32
1     2       Harry Kane    30
2     3    Sergio Aguero    21
3     4      Jamie Vardy    20
4     5  Raheem Sterling    18

In [6]:
innerMergedDF = pd.merge(df1, df2, on=["Player"])
innerMergedDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14 entries, 0 to 13
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        14 non-null     object
 1   club          14 non-null     object
 2   age           14 non-null     int64
 3   position      14 non-null     object
 4   position_cat  14 non-null     int64
 5   market_value  14 non-null     float64
 6   page_views    14 non-null     int64
 7   fpl_value     14 non-null     float64
 8   fpl_sel       14 non-null     object
 9   fpl_points    14 non-null     int64
 10  region        14 non-null     float64
 11  nationality   14 non-null     object
 12  new_foreign   14 non-null     int64
 13  age_cat       14 non-null     int64
 14  club_id       14 non-null     int64
 15  big_club      14 non-null     int64
 16  new_signing   14 non-null     int64
 17  Rank          14 non-null     int64
 18  Stat          14 non-null     int64
dtypes: float64(3), int64(11), object(5)
memory usage: 2.2+ KB

In [7]:
innerMergedDF.head(20)

,Player,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing,Rank,Stat
0,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2.0,France,1,3,1,1,0,8,14
1,Glenn Murray,Brighton+and+Hove,33,CF,1,3.5,496,6.0,1.30%,0,1.0,England,0,5,3,0,0,10,12
2,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2.0,Belgium,0,3,5,1,0,10,12
3,Jamie Vardy,Leicester+City,30,CF,1,15.0,2988,8.5,1.50%,161,1.0,England,0,4,9,0,0,4,20
4,Riyad Mahrez,Leicester+City,26,RW,1,30.0,1753,8.5,1.70%,120,4.0,Algeria,0,3,9,0,0,10,12
5,Roberto Firmino,Liverpool,25,SS,1,38.0,2196,8.5,20.30%,180,3.0,Brazil,0,3,10,1,0,7,15
6,Mohamed Salah,Liverpool,25,RW,1,35.0,1117,9.0,12.40%,0,4.0,Egypt,1,3,10,1,0,1,32
7,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3.0,Argentina,0,4,11,1,0,3,21
8,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1.0,England,0,2,11,1,0,5,18
9,Gabriel Jesus,Manchester+City,20,CF,1,30.0,4254,10.5,15.20%,67,3.0,Brazil,0,1,11,1,1,9,13
10,Romelu Lukaku,Manchester+United,24,CF,1,50.0,3727,11.5,45.00%,221,2.0,Belgium,0,2,12,1,0,6,16
11,Marko Arnautovic,Stoke+City,28,LW,1,15.0,579,7.0,0.70%,117,1.0,England,0,4,15,0,0,14,11
12,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1.0,England,0,2,17,1,0,2,30
13,Son Heung-Min,Tottenham,25,LW,1,30.0,2185,8.0,1.60%,174,4.0,South Korea,0,3,17,1,0,10,12

In [8]:
outerMergedDF = pd.merge(df1, df2, on=["Player"], how='outer')
outerMergedDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 461 entries, 0 to 460
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        461 non-null    object
 1   club          461 non-null    object
 2   age           461 non-null    int64
 3   position      461 non-null    object
 4   position_cat  461 non-null    int64
 5   market_value  461 non-null    float64
 6   page_views    461 non-null    int64
 7   fpl_value     461 non-null    float64
 8   fpl_sel       461 non-null    object
 9   fpl_points    461 non-null    int64
 10  region        460 non-null    float64
 11  nationality   461 non-null    object
 12  new_foreign   461 non-null    int64
 13  age_cat       461 non-null    int64
 14  club_id       461 non-null    int64
 15  big_club      461 non-null    int64
 16  new_signing   461 non-null    int64
 17  Rank          14 non-null     float64
 18  Stat          14 non-null     float64
dtypes: float64(5), int64(9), object(5)
memory usage: 72.0+ KB

In [9]:
outerMergedDF.head(50)

,Player,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing,Rank,Stat
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3.0,Chile,0,4,1,1,0,NaN,NaN
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2.0,Germany,0,4,1,1,0,NaN,NaN
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2.0,Czech Republic,0,6,1,1,0,NaN,NaN
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1.0,England,0,4,1,1,0,NaN,NaN
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2.0,France,0,4,1,1,0,NaN,NaN
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2.0,Spain,0,2,1,1,0,NaN,NaN
6,Olivier Giroud,Arsenal,30,CF,1,22.0,2230,8.5,2.50%,116,2.0,France,0,4,1,1,0,NaN,NaN
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2.0,Spain,0,4,1,1,0,NaN,NaN
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2.0,Germany,0,3,1,1,1,NaN,NaN
9,Alex Iwobi,Arsenal,21,LW,1,10.0,1812,5.5,1.00%,89,4.0,Nigeria,0,1,1,1,0,NaN,NaN
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2.0,Switzerland,0,2,1,1,0,NaN,NaN
11,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1.0,England,0,2,1,1,0,NaN,NaN
12,Jack Wilshere,Arsenal,25,CM,2,18.0,1759,5.5,0.00%,61,1.0,England,0,3,1,1,0,NaN,NaN
13,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1.0,Wales,0,3,1,1,0,NaN,NaN
14,Francis Coquelin,Arsenal,26,DM,2,15.0,549,4.5,1.70%,52,2.0,France,0,3,1,1,0,NaN,NaN
15,Gabriel Paulista,Arsenal,26,CB,3,13.0,552,5.0,0.10%,45,3.0,Brazil,0,3,1,1,0,NaN,NaN
16,Kieran Gibbs,Arsenal,27,LB,3,10.0,489,5.0,0.50%,45,1.0,England,0,3,1,1,0,NaN,NaN
17,Santi Cazorla,Arsenal,32,CM,2,12.0,943,7.0,0.10%,38,2.0,Spain,0,5,1,1,0,NaN,NaN
18,Danny Welbeck,Arsenal,26,CF,1,15.0,1521,7.5,0.50%,37,1.0,England,0,3,1,1,0,NaN,NaN
19,Rob Holding,Arsenal,21,CB,3,7.0,666,5.0,1.70%,32,1.0,England,0,1,1,1,1,NaN,NaN
20,Mohamed Elneny,Arsenal,25,DM,2,10.0,683,4.5,0.80%,26,4.0,Egypt,0,3,1,1,0,NaN,NaN
21,Lucas Perez,Arsenal,28,CF,1,15.0,2055,7.5,0.10%,20,2.0,Spain,0,4,1,1,1,NaN,NaN
22,Emiliano Martinez,Arsenal,24,GK,4,1.0,372,4.0,4.20%,8,3.0,Argentina,0,2,1,1,0,NaN,NaN
23,David Ospina,Arsenal,28,GK,4,7.0,544,5.0,0.20%,2,3.0,Colombia,0,4,1,1,0,NaN,NaN
24,Carl Jenkinson,Arsenal,25,RB,3,5.0,561,4.5,0.40%,2,1.0,England,0,3,1,1,0,NaN,NaN
25,Per Mertesacker,Arsenal,32,CB,3,6.0,702,5.0,1.00%,1,2.0,Germany,0,5,1,1,0,NaN,NaN
26,Sead Kolasinac,Arsenal,24,LB,3,15.0,618,6.0,6.90%,0,2.0,Bosnia,1,2,1,1,0,NaN,NaN
27,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2.0,France,1,3,1,1,0,8.0,14.0
28,Joshua King,Bournemouth,25,SS,1,8.0,997,7.5,10.40%,178,2.0,Norway,0,3,2,0,0,NaN,NaN
29,Jermain Defoe,Bournemouth,34,CF,1,5.0,3213,8.0,15.00%,166,1.0,England,0,6,2,0,0,NaN,NaN
30,Charlie Daniels,Bournemouth,30,LB,3,3.0,185,5.0,19.80%,134,1.0,England,0,4,2,0,0,NaN,NaN
31,Artur Boruc,Bournemouth,37,GK,4,1.0,436,4.5,6.90%,120,2.0,Poland,0,6,2,0,0,NaN,NaN
32,Steve Cook,Bournemouth,26,CB,3,5.0,184,5.0,2.00%,112,1.0,England,0,3,2,0,0,NaN,NaN
33,Junior Stanislas,Bournemouth,27,LW,1,4.5,315,6.0,0.60%,107,1.0,England,0,3,2,0,0,NaN,NaN
34,Adam Smith,Bournemouth,26,RB,3,5.0,200,5.0,0.90%,104,1.0,England,0,3,2,0,0,NaN,NaN
35,Ryan Fraser,Bournemouth,23,LW,1,5.0,516,5.5,1.60%,100,2.0,Scotland,0,2,2,0,0,NaN,NaN
36,Simon Francis,Bournemouth,32,RB,3,2.5,167,4.5,4.00%,89,1.0,England,0,5,2,0,0,NaN,NaN
37,Benik Afobe,Bournemouth,24,CF,1,10.0,528,6.0,0.70%,88,4.0,Congo DR,0,2,2,0,0,NaN,NaN
38,Harry Arter,Bournemouth,27,CM,2,2.5,666,5.0,0.90%,84,2.0,Ireland,0,3,2,0,0,NaN,NaN
39,Marc Pugh,Bournemouth,30,LW,1,2.0,140,5.0,0.10%,64,1.0,England,0,4,2,0,0,NaN,NaN
40,Callum Wilson,Bournemouth,25,CF,1,10.0,337,6.0,0.20%,63,1.0,England,0,3,2,0,0,NaN,NaN
41,Nathan Ake,Bournemouth,22,CB,3,8.0,1274,5.0,11.50%,55,2.0,Netherlands,0,2,2,0,0,NaN,NaN
42,Dan Gosling,Bournemouth,27,CM,2,3.0,184,5.0,0.10%,49,1.0,England,0,3,2,0,0,NaN,NaN
43,Andrew Surman,Bournemouth,30,CM,2,2.0,154,4.5,1.10%,44,1.0,England,0,4,2,0,0,NaN,NaN
44,Jordon Ibe,Bournemouth,21,RW,1,8.0,504,5.0,0.40%,36,1.0,England,0,1,2,0,0,NaN,NaN
45,Lewis Cook,Bournemouth,20,CM,2,6.0,243,4.5,0.80%,17,1.0,England,0,1,2,0,0,NaN,NaN
46,Lys Mousset,Bournemouth,21,CF,1,4.0,131,5.0,0.10%,14,2.0,France,0,1,2,0,0,NaN,NaN
47,Adam Federici,Bournemouth,32,GK,4,1.0,126,4.0,1.50%,8,4.0,Australia,0,5,2,0,0,NaN,NaN
48,Max Gradel,Bournemouth,29,LW,1,7.0,287,5.0,0.10%,8,4.0,Cote d'Ivoire,0,4,2,0,0,NaN,NaN
49,Tyrone Mings,Bournemouth,24,CB,3,5.0,422,4.5,0.40%,4,1.0,England,0,2,2,0,0,NaN,NaN

In [27]:
innerMergedDF.to_csv("inner_merged_output.csv", index=False)
outerMergedDF.to_csv("outer_merged_output.csv", index=False)